### ISSUE TITLE
Sticky element

### ISSUE THREAD

**Issue by zr87** [ericferreira1992/ag-virtual-scroll#1]
Could you please improve component to support position sticky?
Something like [this](http://html5-demos.appspot.com/static/css/sticky.html)

However, the sticky element disappears when scrolled out of viewport.

So the sticky element in the list (for example a selected list item) should kept in the DOM and not taken out when scrolling around the list.

**Comment by ericferreira1992** [comment]
I think that could be done, but I'm will be need to create other component for the data items, something like ``<ag-vs-item></ag-vs-item>``. Also you need inform an optional ``@Input`` named ``sticky``, in which you will put the logical condition for this to happen.

Example:
```html
<ag-virtual-scroll #vs [items]="items" height="350px" min-row-height="50">
   <ag-vs-item *ngFor="let item of vs.items" [sticky]="item === 'something'">
      <span>{{ item }}</span>
   </ag-vs-item>
</ag-virtual-scroll>
```
This way the item will be fixed at the top as long as it is ``[sticky]="true"`` or another item with ``[sticky]="true"`` appears.

Is that what you wanted?

**Comment by zr87** [comment]
Yes, exactly!

**Comment by ericferreira1992** [comment]
@zr87 
Can you wait a few days until I do this? I am solving some personal problems and I can not solve this immediately.

Thanks.

**Comment by zr87** [comment]
Sure! Take your time!

**Comment by ericferreira1992** [comment]
@zr87. Hey There!!

The **ag-virtual-scroll** `sticky` feature were done!
Update **ag-virtual-scroll** in your package.json to 1.0.2.
If you find any issue, please open a new topic about it in order to me fix it.
After you try using the sticky, let me know what you think.

**Comment by zr87** [comment]
Hey Eric! Look great! 
One tiny feature would be wanted for sticky part. I'll open a new issue for it.
