### ISSUE TITLE
Not compatible with angular 12

### ISSUE THREAD

**Issue by ada3m0n666** [ericferreira1992/ag-virtual-scroll#10]
Depency problem with angular animation

**Comment by jordi72** [comment]
Same issue, 
![Screenshot from 2022-03-01 12-19-35](https://user-images.githubusercontent.com/8350580/156160031-f0a79626-7e79-4c23-9e17-6f010a1e4f20.png)

**Comment by ericferreira1992** [comment]
Hello Guys. I will migrate ag-virtual-scroll to lastest Angular version. So, I must you wait for it. Thanks!

**Comment by ericferreira1992** [comment]
Hey everyone! I'm back, and I brought with me the information about the lib update. The AgVirtualScroll has been updated and it's ready to you update on your application.

**Comment by graphefruit** [comment]
Gonna update tomorrow, great! THanks

**Comment by ericferreira1992** [comment]
I will close that issue. If you have any more problems, please open a new issue and report it. Thanks!
