### ISSUE TITLE
Only displaying 3 items with height 100%

### ISSUE THREAD

**Issue by dePablobernat** [ericferreira1992/ag-virtual-scroll#18]
> Hey Eric,
> 
> Thank you for your response. 
> 
> 1.) I am using angular 14. If I use min-row-height the application doesn't compile. 
> <ag-virtual-scroll #vs [items]="caseItems" height="100%" min-row-height="50" class="box-border">
>   <ui-case-list-item
>     *ngFor="let item of vs.items"
>     [case]="item"
>     >
>   </ui-case-list-item>
> </ag-virtual-scroll>
> If I use 100% in height, I only can see 3 items. I think it because of the min-row-height. Did you have a similar problem?
> 
> Thank you and best regards
> 
> _Originally posted by @Ancadea in https://github.com/ericferreira1992/ag-virtual-scroll/issues/14#issuecomment-1234195450_

Hello @ericferreira1992 I'm using your virtual-scroll package and works as a charm. But still I have the same issue as @Ancadea commented. If I set the element height to 100% I'm only able to see 3 items. If i scroll a tiny bit it autosizes the column to the expected height.
What could be happening?

My list is displayed on a container with auto-calculated height and if I set the element .item-container to be 100% in css does fill the space but only 3 elements are rendered.
```
<ag-virtual-scroll
  #vs
  [items]="items"
  min-row-height="109"
  height="100%"
  class="box-border"
>
   <item-card
      *ngFor="let item of vs.items; trackBy: trackByItemFn"
      [attr.data-testid]="'item-card'"
      [card]="item"
      (itemClicked)="
         onClickItemCard({ event: $event, columnId: groupItem.id })
       "
       [hiddenDeleteButton]="
          facade.filters.grouped_by !== 'aggregation_level'
       "
       (deleteItemClicked)="onClickDeleteItemCard($event, groupItem.id)"
    >
    </item-card>
 </ag-virtual-scroll>
 ```
I've been testing with the released version 1.5.2 with angular 14+
Thank you very much!

**Comment by ericferreira1992** [comment]
Hello @dePablobernat. Its happen because when you set `height="100%"` and no other parent element have a specific height defined (but not 100%), the `ag-virtual-scroll` (and any other HTML element) can't get exactly height, and then its tends to increse its height until the end of content. That package isn't prepared to deal with parent scroll, the tip is always you will set height 100% in `ag-virtual-scroll` check if some parent has a specific height, even if that's `100vh`.

@Ancadea, maybe it can be usefull for you.

**Comment by dePablobernat** [comment]
Bingo! You got it all right! I modified parent size in a explicit way and now your library is able to calculate the size correctly.

Thank you very much for the needed help! Issue solved!
