### ISSUE TITLE
Support for angular 15 and onwards.

### ISSUE THREAD

**Issue by michael-roewin** [ericferreira1992/ag-virtual-scroll#20]
Hi Eric,

I'd like to ask if this library will provide support for angular 15 and onwards.

Best regards,
Michael Tan

**Comment by ericferreira1992** [comment]
@michael-roewin hello!
Yes, it will provide soon.
 Thanks!

**Comment by michael-roewin** [comment]
Hi @ericferreira1992,
Thank you for confirming! And thank you also for creating this component :)

**Comment by michael-roewin** [comment]
Hi @ericferreira1992,

I'd like to help update this library to support angular 15. Let me know if its possible.

Thanks,
Michael

**Comment by ericferreira1992** [comment]
@michael-roewin I just realesed the new version of package, witch is compatible with Angular v15. The `ag-virtual-scroll` is in `v1.6.0` on `npm`, do the update.

**Comment by michael-roewin** [comment]
Thanks so much @ericferreira1992! :)
