### ISSUE TITLE
Cache system and pre-loading

### ISSUE THREAD

**Issue by Salvatore-Als** [ericferreira1992/ag-virtual-scroll#22]
Hello,
Do you think it would be possible to have a system that caches old loaded data ?
With the possibility of invalidating the cache (in case of page change).

This cache system would make it possible to no longer have to re-create the components, especially in the event of an ecoponent creation via the TemplateRef.createComponent.

Best Regards,

**Comment by ericferreira1992** [comment]
@Salvatore-Als. Maybe something that would help in virtualization elements performance would be really fine. But everything different this isn't `ag-virtual-scroll`'s problem, it's would be a business rule.
