### ISSUE TITLE
How to add ag-virtual-scroll as sub content?

### ISSUE THREAD

**Issue by AlexTerry1024** [ericferreira1992/ag-virtual-scroll#26]

**Comment by AlexTerry1024** [comment]
Hello, How are you?

I have some header content and bottom content and array data and I want to use it as full scroll.
In this case, How to use ag-virtual-scroll?

Thank you.

**Comment by ericferreira1992** [comment]
@AlexTerry1024, I didn't understand well, can you give me some example?

**Comment by AlexTerry1024** [comment]
![image](https://github.com/ericferreira1992/ag-virtual-scroll/assets/31697138/c828c103-f4d8-43d6-9dfc-9417c7baf36e)

I want the function like this

**Comment by AlexTerry1024** [comment]
There is any way to have Content Before and Content After with ag-virtual-scroller?

**Comment by ericferreira1992** [comment]
Ok, I could understand now. But `AgVirtualScroll` isn't prepared to do it, it's not possible. But you can do a workaround to make this work, would be considering the first item (or last) on the list as "Content before" (or "Content after"). Did you understand?
