### ISSUE TITLE
Support Angular 18 please :)

### ISSUE THREAD

**Issue by graphefruit** [ericferreira1992/ag-virtual-scroll#27]
Hey @ericferreira1992,
after Angular 18 is out, i'd be happy if you could update the library to the latest angular dependency.

Thank you so much for taking this into account & for building this great solution, works like a charm on my side
Thanks
Lars

**Comment by ericferreira1992** [comment]
Hey @graphefruit! I will do the update to v18. Thanks for remembering. I appreciate your support as always. 🙂

**Comment by graphefruit** [comment]
> Hey @graphefruit! I will do the update to v18. Thanks for remembering. I appreciate your support as always. 🙂

Awesome! Thank you so so much<3

**Comment by ericferreira1992** [comment]
@graphefruit ag-virtual-scroll v1.9.0 with Angularv18 supports is available on NPM. 🙂

**Comment by graphefruit** [comment]
Thank you so much! Awesome <3
