### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when using Angular Signals

### ISSUE THREAD

**Issue by OJP98** [ericferreira1992/ag-virtual-scroll#29]
# I'm getting RuntimeError NG0100 when using this component on my list.

The component works great, i'm just concerned about a height error getting logged in the console. Apparently i'm using it correctly

## Description

![ErrorInBrowser](https://github.com/user-attachments/assets/0d3a97a3-b154-4404-94f8-1081e64838c3)

I have a list in a service (timezones.service.ts) that's getting fetched internally from a library in the constructor. It then gets assigned to a variable in the component (location-picker.component.ts) where i'm trying to get the virtual scroll from. It's assigned in the constructor as well (using signals).

I'm using a signal inside in the service since it's being shared between multiple components. This list returns 311 items, all of which then get mapped into a custom button component.

_timezones.service.ts_
```typescript
import { getAllTimezones } from 'countries-and-timezones';

...

export class TimezonesService {
  public locations = signal<CityTimezone[]>([]);
  constructor() {
    this.locations.set(getAllTimezones());
  }
}
```

_location-picker.component.ts_
```typescript

import { AgVirtualScrollModule } from 'ag-virtual-scroll';
...
  imports: [
    NgFor,
    AgVirtualScrollModule,
    LocationButtonComponent,
  ],
...
export class LocationPickerComponent {
  public locations: CityTimezone[];
  constructor(private timezonesService: TimezonesService) {
    this.locations = this.timezonesService.locations();
  }
}
```

_location-picker.component.html_
```html
<div
  class="dropdown-content w-full overflow-auto rounded-box bg-base-200 shadow-inner"
>
  <ul class="menu menu-dropdown">
    <ag-virtual-scroll #vs [items]="locations" height="384px" [min-row-height]="34">
      <app-location-button
        *ngFor="let location of vs.items"
        [class.hidden]="location.selected"
        [cityTimezone]="location"
        (click)="clearInput()"
      />
    </ag-virtual-scroll>
    @if (noResults()) {
      <li class="disabled">
        <button>No results found</button>
      </li>
    }
  </ul>
</div>
```

## App Visualization

I'm using the button component height, which is ~34px.

![AppImg](https://github.com/user-attachments/assets/ef8273d0-6139-42e1-8fce-0978533a0720)

## Environment
 
![EnvImg](https://github.com/user-attachments/assets/1e80dca1-a8ff-48b3-85b9-36d684df1666)

Tested on both Chrome 130.0.6723.70 and Microsoft Edge Version 130.0.2849.46

**Comment by graphefruit** [comment]
> The component works great, i'm just concerned about a height error getting logged in the console. Apparently i'm using it correctly

I got this issue aswell since several years, I just ignore it, but maybe there are ideas here.

**Comment by ericferreira1992** [comment]
Hey guys. Its usually happens when we change `@Input height` many times or are using function to define `height` value. But for @OJP98's example, that's not the case. But you can ignore this erros, because this dont interfere with component operation, in production this error doesn't show.
