### ISSUE TITLE
Input and output properties of virtual scroll are private

### ISSUE THREAD

**Issue by kkEngine** [ericferreira1992/ag-virtual-scroll#6]
Cant bind from html to components properties. Angular says it's private. Angular 11+
html:
```
<ag-virtual-scroll #vs [items]="items" [height]="myHeight" [min-row-height]="minRow" class="box-border">
</ag-virtual-scroll>
```
At source code:
```
@Input('min-row-height') private minRowHeight: number = 40;
@Input('height') private height: string = 'auto';
@Input('items') private originalItems: any[] = []; 
```

Thanks for component.

**Comment by ericferreira1992** [comment]
@kkEngine 
Sorry for late. This fix is in [ag-virtual-sroll](https://www.npmjs.com/package/ag-virtual-scroll) version 1.3.2. Update dependency and check it.
