### ISSUE TITLE
Please add the licence file here

### ISSUE THREAD

**Issue by graphefruit** [ericferreira1992/ag-virtual-scroll#7]
Hi there!
Thanks for this wonderful plugin, it works realy realy good.
From the npm-registry it says "MIT-Licence", therefore could you please add this licence-file on this repo aswell?
Thanks!
Lars

**Comment by ericferreira1992** [comment]
@graphefruit  
License was added in the version 1.3.2 of [ag-virtual-sroll](https://www.npmjs.com/package/ag-virtual-scroll). Update dependency and check it. Then tell me if it solved your need.
Thanks a lot!

**Comment by graphefruit** [comment]
Perfect thank you!
I gonna insert another enhanchment later these day which occured while testing.
Thanks for your fast response!
Really appreciate this!
