### ISSUE TITLE
Compile fails after updating vom 1.3.0 to 1.3.2

### ISSUE THREAD

**Issue by graphefruit** [ericferreira1992/ag-virtual-scroll#8]
Hi there!
I just wanted to update to the latest version, but when compiling with ionic-framework it says:
```
[ng] Compiling ag-virtual-scroll : module as esm5
[ng] Warning: Invalid constructor parameter decorator in /xxx/node_modules/ag-virtual-scroll/fesm2015/ag-virtual-scroll.js:
[ng]  () => [
[ng]     { type: ElementRef },
[ng]     { type: ApplicationRef }
[ng] ]
[ng] Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected AgVsItemComponent to have an inner class declaration
```
With Version 1.3.0 the compile is working normaly

**Comment by ericferreira1992** [comment]
@graphefruit 
I'm just build an Angular aplication in version 11, and I had no problems, the build was successfully.
Send me the output in `ng --version` of your application.

My example project looks like this:
![image](https://user-images.githubusercontent.com/12420366/111816050-20791480-88bb-11eb-9f5e-47a1a320bf60.png)

**Comment by graphefruit** [comment]
Hey there!
here the information :)
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.15
Node: 10.13.0
OS: darwin x64

Angular: 9.1.13
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.901.15
@angular-devkit/build-optimizer   0.901.15
@angular-devkit/build-webpack     0.901.15
@angular-devkit/core              9.1.15
@angular-devkit/schematics        9.1.15
@angular/cli                      9.1.15
@ngtools/webpack                  9.1.15
@schematics/angular               10.2.0
@schematics/update                0.901.15
rxjs                              6.6.6
typescript                        3.8.3
webpack                           4.42.0
```

**Comment by ericferreira1992** [comment]
You need to migrante your angular project to v11. Because ag-virtual-scroll was build in version 11 of Angular.
I'm waiting for your feedback.

**Comment by graphefruit** [comment]
Hey @ericferreira1992 thanks for your feedback.
Sadly Ionic doesn't support Angular 11 perfectly yet (even when it says something different on websites), therefore I cant update just yet :(
So I think there will be no other work around to stick on the old version?

**Comment by ericferreira1992** [comment]
As it has already been upgraded to the higher version, there is no way to fix bugs in the old versions. 😔
If you can to fork the ag-virtual-scroll repository on github and rollback to v9 of Angular, you can use your forked repository as a dependency.

**Comment by graphefruit** [comment]
Hi there,
sorry for the late response.
So I need to stick with 1.3.0 as long as ionic supports angular 11 completely
