### ISSUE TITLE
Scroll doesn't know when to end

### ISSUE THREAD

**Issue by graphefruit** [ericferreira1992/ag-virtual-scroll#9]
Hi there!
First of all:
I really really love this plugin.
I have tested all I could find, and this is the only one which is fast and handels different container heights.

Whats my use case?
I develop an Android aswell as an iOS app, where you can track all your coffee-parameters, and depending on which parameter you entered, the card-element will be bigger or smaller.

The cards are used from the ionic-framework and have margin/paddings.

The issue just occures on Android, not on iOS, nor on a normal browser.

If you scroll fast, like a fast swipe up, and the scroll-container comes to the end, he calculates and the result you can see in this video:

https://user-images.githubusercontent.com/6260244/111802668-8b801680-88ce-11eb-8ac6-9fde494092b7.mp4

After I searched where this issue comes from and how to fix it I found out that all of my repeated-card had a `margin-top: 10px` and a `margin-bottom:10px` after disabling them, the scroll event worked perfectly without stutters.

Therefore my work around was to add another element with `<div style="height:10px"></div>` and the plugin could calculate everything exactly.

I hope this helps
Thanks for your help!
Greetings
Lars

**Comment by ericferreira1992** [comment]
@graphefruit 
Hello!
Can you provide an example with the same issue (but on desktop browser) in Stackblitz or another playground code to I can see? Because I need to simulate something that is as close as possible to the error.
Thanks for feedback.

**Comment by graphefruit** [comment]
Hi there,

I tried some days now to reproduce this issue in the web for you, but with no success.
Maybe you can give me a hint where I could grab into myself to debug.
At least I could identify the problem with padding/margin of top/bottom already.

**Comment by jordi72** [comment]
I had the same issue and i solved it by wrapping the "item" is a div element.

Buged Code:
```
<ag-virtual-scroll #vs [items]="data" height="100px" [min-row-height]="minRowHeight">
     <p *ngFor="let item of vs.items">{{item}}</p>
</ag-virtual-scroll>
```

Working Code:
```
<ag-virtual-scroll #vs [items]="data" height="100px" [min-row-height]="minRowHeight">
     <div *ngFor="let item of vs.items">
            <span>{{item}}</span>
     </div>
</ag-virtual-scroll>
```

**Comment by ericferreira1992** [comment]
Hello, Guys!
@jordi72, exactly! You need wrap the content with a div ou ag-vs-item (native from lib). Because AgVirtualScroll needs to recognize the repetition elements to virtualize them all.
Take a look at the **Important** block from documentation:
![image](https://user-images.githubusercontent.com/12420366/156427393-125b2a45-a0f1-49c4-a026-cecd91d205e0.png)

**Attention**: I updated ag-virtual-scroll to lastest Angular version (v13)
